bridge: Add incoming clients to bridge fdb
westermo/dhcp-helper pull request #8
Opened 2018-06-07 15:20 UTC by mattiaswal

This is only required if running on a unit that has a switchcore,
that may not always learn the MAC address on DHCP packet.

If you don't have this setup (a normal linux bridge)  this should
not break anything.

2018-06-07 15:30 UTC, jonasj76 requested changes

2018-06-07 15:30 UTC, jonasj76 commented on src/misc.c
> +
Use tab instead of space

2018-06-07 15:30 UTC, jonasj76 commented on src/misc.c
> +
Use tab instead of space

2018-06-07 15:30 UTC, jonasj76 commented on src/packet.c
> +
Use tab instead of space

2018-06-07 16:15 UTC, jonasj76 commented on src/misc.c
> +		nl_socket_free(sk);
missing `nl_addr_put(addr)` and maybe return `err` instead of 1?

2018-06-07 16:15 UTC, jonasj76 commented on src/misc.c
> +
missing `nl_addr_put(addr)` and `nl_socket_free(sk)`

2018-06-07 16:15 UTC, jonasj76 commented on src/misc.c
> +                return 1;
return `err` ?

2018-06-07 16:15 UTC, jonasj76 commented on src/misc.c
> +		return 1;
return `err`?

2018-06-07 20:00 UTC, mattiaswal commented
Thanks, will fix that.

2018-06-08 08:55 UTC, jonasj76 approved these changes

2018-06-08 08:56 UTC, merged